name: Deploy

on: push

jobs:
  my-job:
    name: Deploy to surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list cwd
        run: |
          ls



      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'ma-web.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}